#!/usr/bin/python

"""
This script is meant to extract the last frame of trajectory from either a .trr file (using gromacs tools) or from a
.gro trajectory file generated by trjconv.
"""
import argparse
import subprocess

parser = argparse.ArgumentParser(description='Grab the last trajectory frame and make a .gro file')

parser.add_argument('-f', '--file', default='wiggle.trr', help = 'Path to input file')
parser.add_argument('-t', '--tpr', default='wiggle.tpr', help = 'Name of .tpr file if extracting from last frame')
parser.add_argument('-i', '--ion', default='NA', help='Name of ion(s) being used to calculate ionic conductivity')
parser.add_argument('-l', '--LC_type', default='HII', help='Type of liquid crystal. Should match that defined in '
                                                           'LC_class.py')
parser.add_argument('-s', '--solv', default='no', help='Is the system solvate?')

args = parser.parse_args()

def extract_last_gro(filename):
    if filename.endswith('.gro'):

        f = open(filename, 'r')

        a = []
        for line in f:
            a.append(line)
        f.close()

        for i in range(0, len(a) - 1):
            if a[i].count('trjconv') != 0:
                trj_line = i

        b = []
        for i in range(trj_line, len(a)):
            b.append(a[i])

        f = open('last_frame.gro', 'w')
        for line in b:
            f.write(line)
        f.close()
    else:
        print 'Incompatible Filetype'

def extract_last_trr(filename, tpr):
    if filename.endswith('.trr'):
        # This section doesn't work
        import subprocess

        # Convert the entire trajectory first
        p1 = subprocess.Popen(["echo", "0"], stdout=subprocess.PIPE)
        p2 = subprocess.Popen(["gmx", "trjconv", "-f", "%s" % filename, "-s", "%s" % tpr, "-o", "wiggle_traj.gro"], stdin=p1.stdout)
        p2.wait()

        import Get_Positions
        # Use get_positions to get the trajectory points, passing in a useless component name
        pos, vel, trj_times, box = Get_Positions.get_positions('wiggle_traj.gro', 'Maclynn', 'HII', 'no')
        print trj_times
        # Run trjconv again, but this time using the time of the last frame
        p3 = subprocess.Popen(["gmx", "trjconv", "-f", "%s" % filename, "-s", "%s" % tpr, "-o", "last_frame.gro",
                              "-b", "%s" % trj_times[len(trj_times) - 1], "-e", "%s" % trj_times[len(trj_times) - 1]])

        p4 = subprocess.Popen(["rm", "wiggle_traj.gro"])
    else:
        print 'Incompatible Filetype'

if __name__ == "__main__":
    if args.file.endswith('.gro'):
        extract_last_gro('%s' % args.file)
    if args.file.endswith('.trr'):
        extract_last_trr('%s' % args.file, '%s' % args.tpr)